apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-event
  labels: &labels
    app.kubernetes.io/name: pool-event
    app.kubernetes.io/component: component-explorer
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: pool-event
          image: ghcr.io/viva-con-agua/pool-event
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: pool-api
            - configMapRef:
                name: pool-event
          ports:
            - name: http
              containerPort: 1323
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1323
          resources:
            limits:
              memory: 400Mi
              cpu: 100m # 10 milli-cores = 1% of a core
