apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pool-event-db-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
